// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi78gL2Oky-ADWH9xpqgUuwxJaYaadKiM',
    appId: '1:369839462298:web:ae4d3b0a5f9fb2a22c0c23',
    messagingSenderId: '369839462298',
    projectId: 'market-shop-b5e1d',
    authDomain: 'market-shop-b5e1d.firebaseapp.com',
    storageBucket: 'market-shop-b5e1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyTdO2W0SF-Cqd0qqMfgMFK4Czuy_sTaI',
    appId: '1:369839462298:android:6375abe8231d5a1b2c0c23',
    messagingSenderId: '369839462298',
    projectId: 'market-shop-b5e1d',
    storageBucket: 'market-shop-b5e1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvnXBhfA1ZKhZmDuow_uVYIsnYALMpgF4',
    appId: '1:369839462298:ios:d970e450236dada32c0c23',
    messagingSenderId: '369839462298',
    projectId: 'market-shop-b5e1d',
    storageBucket: 'market-shop-b5e1d.appspot.com',
    iosBundleId: 'com.example.marketShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvnXBhfA1ZKhZmDuow_uVYIsnYALMpgF4',
    appId: '1:369839462298:ios:d970e450236dada32c0c23',
    messagingSenderId: '369839462298',
    projectId: 'market-shop-b5e1d',
    storageBucket: 'market-shop-b5e1d.appspot.com',
    iosBundleId: 'com.example.marketShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi78gL2Oky-ADWH9xpqgUuwxJaYaadKiM',
    appId: '1:369839462298:web:8dca4877e2cb60ae2c0c23',
    messagingSenderId: '369839462298',
    projectId: 'market-shop-b5e1d',
    authDomain: 'market-shop-b5e1d.firebaseapp.com',
    storageBucket: 'market-shop-b5e1d.appspot.com',
  );

}